### ISSUE TITLE
Integrate the storing standup API

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#100]
Task Description :- integrate the api endpoint in frontend to store standup data in the database created by admin

DOD :- Admin should be able to create standup from the frontend

**Comment by ayushdevelop** [comment]
completed the integration of api to create standups from frontend
CC : @nishanthmathiyazhagan9704 
PR Link :-https://github.com/code-mancers/g-bot/pull/102
