### ISSUE TITLE
Set a scheduler

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#12]
**Task Description :** 

- On the g-bot application, the scheduler should send a message asking for the standup updates on weekdays 9:30 AM IST
- The following members on the channel should get the notification on g-bot
Members for now : 
  - Ayush 
  - Sujay 
  - Nishanth 
  - Vinu 

**DOD :** 

The User should get the notification on the g-bot application for the Standup Update by 9:30 AM IST 

Note : Please refer the image attached below 

![Image](https://user-images.githubusercontent.com/39298649/188881758-95266e2d-628e-4f00-91a9-3b9e783fc475.png)

**Comment by ayushdevelop** [comment]
Feature for scheduling standup message completed.
PR:-  https://github.com/code-mancers/g-bot/pull/28
CC :- @nishanthmathiyazhagan9704
