### ISSUE TITLE
Creating an API end point for the channel

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#14]
**Task Description :** 

Back end task : 

- When the admin visits the add page in the dashboard , a channel drop down should be displayed 
- This drop down should contain the channels specific to admin workspace 
- backend should provide an end point which returns the channels 

**DOD :** 

- Backend should be able to return the channels specific to admin workspace

**Comment by nishanthmathiyazhagan9704** [comment]
WIP : Adding the test cases

**Comment by ayushdevelop** [comment]
- Developed an api for fetching the channels from slack-workspace.
-  Added unit tests

cc: @nishanthmathiyazhagan9704 
PR Link :- https://github.com/code-mancers/g-bot/pull/60
