### ISSUE TITLE
Postgres spike

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#16]
**Task Description :** 

- Explore Postgres 
- Prisma ORM: https://www.prisma.io/

**Comment by ayushdevelop** [comment]
## Things I learnt in Postgres Spike Task

### Basics

- create a database
- create a table
- how to insert data into a table
- how to fetch all the data 
- how to use where conditions 
- how to sort 
- how to fetch only selected fields from a table
- updating
- deleting

### Associations
- one-to-one
- one-to-many
- many-to-many
