### ISSUE TITLE
Create an end point to fetch the standups from the database

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#18]
**Task description :** 

Back end task : 

- Create an API end point for fetching the standup from the database and showing it on the list page 
- Integrate the API to fetch the standup details 

- When the admin visits the listing page a fetch request will be made to the end point provided by the backend 
- On receiving the request a service will be implemented to fetch the standup data  from the database 

**DOD** : 

- The admin will be able to see the list of standups on the listing page

**Comment by ayushdevelop** [comment]
Endpoint for fetching standup data is completed and running fine, test is also added for the same. Reason for not opening the PR is the branch is made on top of `channel-api` and `channel-members-api` which are not merged yet because of unit testing reason.

CC: @nishanthmathiyazhagan9704
