### ISSUE TITLE
API integration for fetching the channel members

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#23]
**Task Description :** 

FE : 

- API integration to fetch the channel  members based on the channel selected 
- List down the channel members with a check box 

**DOD :** 

- Admin should be able to see the channel members based on the channel selected 
- The members of the channel should be listed with the check box 
- By default the checkbox should be checked 
- If admin unchecks the checkbox of a particular user , the user will not be notified for the standup updates

**Comment by ayushdevelop** [comment]
Integrated the api for fetching channel members on interacting with backend
PR Link:- https://github.com/code-mancers/g-bot/pull/90
cc: @nishanthmathiyazhagan9704
