### ISSUE TITLE
Initiate standup

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#3]
**Task Description:** 
In slack, The application g-bot should be displayed on the left side of the footer. On clicking g-bot, the user should be able to see two tabs on the right side 

- Messages 
- About 

 On clicking the "Messages" tab There should be a question asked to the user "Can you provide updates for the standup ?" with the two buttons 

- Approve 
- Not working 

On clicking the "About " Tab the user should be able to see a detailed summary of the g-bot application with the "configuration " button 

 The user should also be able to run the command " /Standup" to display the "Approve" & "Not Working" buttons if the g-bot failed to notify the user 

**DOD:**  
- The user should be able to see the g-bot application 
- On clicking g-bot the user should be able to see 2 tabs displaying "Messages & About "
- The messages tab should have a question with two buttons displaying " Approve " or "not working " 
- The about tab should have a detailed description of the application 
- The user should also be able to use the "/standup " run command to update the standup 

Note: Please refer to the image attached below 

![Image](https://user-images.githubusercontent.com/39298649/187886152-c91e936c-97b6-4ceb-94a2-038909843eb4.png)

**Comment by ayushdevelop** [comment]
@nishanthmathiyazhagan9704 I will require `botToken` and `signingSecret`

**Comment by nishanthmathiyazhagan9704** [comment]
@ayushdevelop  Please check 

SigningSecret: 4143f21625df60f3bce9a174adcaf311
Token: GkeD3s2t3XtznPyDNrFP9rxW

**Comment by ayushdevelop** [comment]
migrating the code from `nodejs` to `expressjs`

**Comment by nishanthmathiyazhagan9704** [comment]
Blocker: migrating the code from node.js to express.js . (Integrating )

**Comment by ayushdevelop** [comment]
After unsuccessfully implementing numerous solutions with help of @SujayPrabhu96 , I have reported the issue in the relevant discussion thread of Github , will keep on looking for solutions till we hear anything from them

**Comment by ayushdevelop** [comment]
https://github.com/code-mancers/g-bot/pull/8 completed the first ticket of initiating a standup 
cc: @nishanthmathiyazhagan9704
