### ISSUE TITLE
Create docker-compose for gbot repository

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#36]
**Task Description :**  

Create docker-compose for gbot repository which should include all dependencies like postgres, redis, cron, server

DOD :

**Comment by Johnson-Dsouza** [comment]
Error: 
![Image](https://user-images.githubusercontent.com/60909862/191170381-9f60f738-76d2-4603-af45-03aa2ff58e17.png)
