### ISSUE TITLE
Popup for adding the standup

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#4]
**Task Description:** 

In the g-bot application on the Messages tab, the user should be able to click on the "Approve" button. On clicking the approve button a Modal should pop up which will have the standup questions and the input field boxes to update it. 

The following questions 

- How do you feel today?
- What is/are the things that you've done which mattered to the sprint goal since yesterday?
- What is the next important thing that you will do to achieve the sprint goal?
- Any Blockers that need to be addressed by the team?

There should be 2 buttons displayed on the footer of the popup 

- Submit 
- Cancel 

**DOD:** 

- The user should be able to see click on the approve button on the messages tab 
- On clicking approve the modal popup should be displayed with the four question 
- The user should be able to type the standup report on all the input filed boxes 
- The user should be able to click on submit & cancel button 
- On clicking submit the standup response will be updated on the particular channel 
- On clicking the cancel button the modal popup should be closed 

Note: Please refer to the attached image below 

![Image](https://user-images.githubusercontent.com/39298649/187890056-0c9f8088-7457-4425-a135-043fbb719e90.png)

**Comment by ayushdevelop** [comment]
Completed the issue, PR link :- https://github.com/code-mancers/g-bot/pull/20
cc: @nishanthmathiyazhagan9704
