### ISSUE TITLE
Cleanup for the listing page

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#47]
**Task description :**  

- In G-bot application the design template in listing page, the unwanted code for the fields should be cleaned up 
- The page should only contain fields for displaying list of a standup 

**DOD :**

- Listing page should only contain fields related to standup with dummy entries

Note : Please refer the image below 

![Image](https://user-images.githubusercontent.com/39298649/191674695-587223a0-261b-4230-a650-14a6464ae6bb.png)

**Comment by ayushdevelop** [comment]
Cleaned and edited the Listing Page of react-admin template to add fields that provide details for Standup.

cc: @nishanthmathiyazhagan9704 
PR Link :- https://github.com/code-mancers/g-bot/pull/69
