### ISSUE TITLE
Not working response

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#5]
**Task Description:** 

In the g-bot application on the Messages tab, the user should be able to click on the "Not working" button.
On clicking the not working button the user should be reported as "Not working today " on the particular channel 

**DOD:** 

- The user should be able to click on the "Not working" button " 
- On clicking the "Not working button" the user will be reported as " Not working today " instantly on the particular channel 
- The user and the other colleagues will be notified about the person who is not working 

Note: Please refer to the image attached below 

![Image](https://user-images.githubusercontent.com/39298649/187895572-5cc98e6c-40e7-4c86-a394-22b1bd50a319.png)

![Image](https://user-images.githubusercontent.com/39298649/187895621-20b53882-0333-4372-a1a5-1c7d52fee677.png)

**Comment by ayushdevelop** [comment]
Completed the feature of letting user mark themselves as `not working`
PR :- https://github.com/code-mancers/g-bot/pull/25
CC :- @nishanthmathiyazhagan9704
