### ISSUE TITLE
Modifying the edit page

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#50]
**Task Description :**  

- Listing page will list all the standup's along with edit and delete button for each entry
- On clicking the edit button it should redirect to edit page
- In edit page, remove the unwanted sections from the design of template 
- The edit tab should only contain the fields to edit the existing standup 

**DOD :** 

- On clicking the edit button provided on the standup listing page it should redirect to the edit page 
- The edit page should have  edit section 

Note : please refer to the image below 

![Image](https://user-images.githubusercontent.com/39298649/191676103-a474badf-3d97-4954-88ce-e8bde0f1cc99.png)

![Image](https://user-images.githubusercontent.com/39298649/191676313-f26cfc4b-2439-45d9-aa8a-b5b64df5f6a7.png)

**Comment by ayushdevelop** [comment]
Updated the Edit page component to add fields for editing standup.
cc: @nishanthmathiyazhagan9704 
PR Link :- https://github.com/code-mancers/g-bot/pull/68
