### ISSUE TITLE
Deploy Backend

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#63]
Task Description : 

Deploy frontend app or client app main branch on Coolify at [gbot.codemancers.com](http://gbot.codemancers.com)

**Comment by Johnson-Dsouza** [comment]
Created GBot Backend deployed at [gbot.codemancers.com](http://gbot.codemancers.com/) using [coolify.codemancers.co](http://coolify.codemancers.com/)
