### ISSUE TITLE
Add notification

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#70]
**Task Description :** 

Add notification to to the g-bot application whenever the user is adding the standup detail or marking them as not working there should be a instant notification . 

DOD : Add notification response to the application as well in the channel 

Note : Please refer the image below 

![Image](https://user-images.githubusercontent.com/39298649/192959540-beccf7cc-007a-4311-a26a-3b6ef3e5555a.png)

![Image](https://user-images.githubusercontent.com/39298649/192959561-5b6cf9bc-5940-4070-abaf-788ea2cab9d6.png)

**Comment by ayushdevelop** [comment]
completed the feature of updating standup message, once the user submits the response or mark themselves as not working
CC: @nishanthmathiyazhagan9704 
PR Link :- https://github.com/code-mancers/g-bot/pull/73
