### ISSUE TITLE
Deploy frontend

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#79]
Task Description : 

Deploy frontend app or client app main branch on Coolify at [gather.codemancers.com](http://gather.codemancers.com/)

**Comment by Johnson-Dsouza** [comment]
Getting type errors in application logs in **coolify.codemancers.com** server.

**Comment by Johnson-Dsouza** [comment]
Created and deployed GBot Frontend, which can be assigned at [gather.codemancers.com](https://gather.codemancers.com).
