### ISSUE TITLE
Deployment architecutre

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/g-bot#89]

**Comment by Johnson-Dsouza** [comment]
[Architecture Diagram of Gbot](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=AWS-gbot#R7Zltj6M2EMc%2FTaT2xUVgILAvE5LcnbS9rm7Vu7ZvTg44xF2DI2PysJ%2B%2BYzCEpyzZKqlaKatIa%2F8xYzMzP48TRpYfHz4KvN38wkPCRsgIDyNrPkIImciDf0o5ForjPhRCJGhYSOZJeKavRIuGVjMakrQxUHLOJN02xYAnCQlkQ8NC8H1z2Jqz5qxbHJGO8Bxg1lW%2F01BuCtVzjJP%2BidBoU85sGvpKjMvBWkg3OOT7mmQtRpYvOJdFKz74hCnnlX4p7lueuVotTJBEXnLDr9mX3cvnXfLti%2FVptZxYf77a5gdtZYdZph94%2Bv0ZhGkQ8AzsFiuXx9IdW04TmbvUmcEHZvSNkQNXfNUbI6cltPtuUzC7PWWjKbT7blMw2%2BbN1vxme4E1odNrmDda8xu1BcLHmvFMMpoQv0o%2BA8RI4JBCUHzOuAAt4Ql4b7aRMYOeCc39hkryvMWB8uoewAFtzROp099EZV87XlmFBJcY5hLaRh4JIhY7UgSkGMMY3qZ0Vd0lSJCJlO7IV5IWxpUKqbhV7fgQKWrHeJ%2Fa40jwbJsv%2FzPM1Xv1B9ZpASak4C%2BkfMQRsvw5QhNbLZwy1nr0HRGSAlNTRiNlWXI1EdY9Rta5RfAHTaLHvDe3DO2DvilCnG5IqB%2Bmy0GZ1DArOdQkzcVHwmMixRGGlFdLRvUmZevu%2FkT8pNQ2NdptT4tY7zJRZfoEIjQ0i%2B%2FgEnW4%2FEoiCmG5A3kHsgakKLKih0fTdhez6U15rKaoeDSvxOOkyaPX5dGZ9PFo3IpHq8Pjtyf%2FDuMdxjqMu23QRyKUCc%2B8bWWcTmfuzBuujG%2FWmovxtAerZVUY63Ra6FZ02h06n7IVo4GiM1sl5H6OvZPaIDVV5qg8%2FjgNfs6xLQ1fxDDoi4eltZhcD%2BRqnmsfcdvQViW2Tq3RQ21149WpdTrUdjDtzcuGa0q%2FP%2BIVYU88pTI%2FD81XXEoeDwYmICr5mlndk1XWmASoG%2F2l4zmWfR6VCzdg%2B73BdAc3YNR3PDIt60ahnPSEcsJUyq%2BgEanGwq80mKKSq3GiVH4KOGd0fRwHPCQxTgIiUmjHP3eyA7wlW6FrcKuj0FN2O%2BFvZ0lMw1BN07vFwZ6RhO%2Btsu8OsomcJrEP3TCbTl%2BdvRWwD8PAkjAi5W7PhdzwiCeYLU5qy3mnMY9cgZlH8S8i5VHXEJxJ3ozx2c0w5ZkIyBvrd4txEouIvBUq%2FZOlepY3AyUIwxJqUmMVV%2Fe6O%2Bz1wU2w5r4L98NBkmD7M4zZYon6dszXTJAxlPDCeLvEX%2Blb4gfU%2BpqIbKdLSF9Nc29FSPmr9b9LBLhQHH%2FX9%2BedP1QHDny6Oz%2FUL86PQ8eKQZK8C0ky%2F1MkecMk9YByFqoOM0yNnOHgJcpDWiNlnf%2Bdpa%2BArXy%2FgPoOoIbhGUt95i1eI3SOQm0KKU%2FdMYUzMJRPxrPwStS1Dh%2FIQeMLsXOcW2HXfY3xWwoh%2Bb8cGP7B1tc6zlffres%2FWV%2FnbADd00uq%2FFrtVZ%2B1%2BBs%3D)
